config/routes.rb
Rails.application.routes.draw do
  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    # respond_to do |format|
    #   if @note.save
    #     format.html { redirect_to @note, notice: 'Note was successfully created.' }
    #     format.json { render :show, status: :created, location: @note }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @note.errors, status: :unprocessable_entity }
    #   end
    # end

		if @note.save
			redirect_to @note, notice: "投稿が保存されました"
		else
			render :new
		end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    # respond_to do |format|
    #   if @note.update(note_params)
    #     format.html { redirect_to @note, notice: 'Note was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @note }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @note.errors, status: :unprocessable_entity }
    #   end
    # end
		if @note.update(note_params)
			redirect_to @note, notice: "投稿が更新されました"
		else
			render :edit
		end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    # respond_to do |format|
    #   format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
		redirect_to notes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatebook2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  ユーザーID
  <%= f.collection_select :user_id, User.all, :id, :id, {prompt: true}, {class: "form-control user-id-field"} %>
  タイトル
  <%= f.text_field :title, { class: "form-control title-field" } %>
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>
  <%= f.submit "保存", { class: "btn primary-btn" } %>
<% end %>

app/views/notes/_note.html.erb
<li>
  <%= image_for(note.user) %>
  <span class="user-name">
    <%= note.user.name %>
  </span>
  <span class="content">
    <%= link_to note.title, note_path(note.id) %>
  </span>
</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <%= render @notes %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<h2>タイトル</h2>
<p><%= @note.title %></p>
<h2>内容</h2>
<p><%= @note.content %></p>

<%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
<%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>